### ISSUE TITLE
希望移植一下插件

### ISSUE THREAD

**Issue by xiaowine** [zhang-anzhi/CoolQAPI#2]
bbs.onoqq.com这个机器人和酷q比较像，希望移植一下

**Comment by xiaowine** [comment]
如果这不是coolapi负责的范围，请见谅

**Comment by zhang-anzhi** [comment]
没有发现onoqq这个机器人提供了给非插件的httpapi
也没有找到合适的插件
找到了可以告诉我

**Comment by xiaowine** [comment]
> 没有发现onoqq这个机器人提供了给非插件的httpapi
> 也没有找到合适的插件
> 找到了可以告诉我

http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http

**Comment by zhang-anzhi** [comment]
> [http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http这个可以吗](http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http%E8%BF%99%E4%B8%AA%E5%8F%AF%E4%BB%A5%E5%90%97)

功能不全。

**Comment by xiaowine** [comment]
> > [http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http这个可以吗](http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http%E8%BF%99%E4%B8%AA%E5%8F%AF%E4%BB%A5%E5%90%97)
> 
> 功能不全。

你能说说具体要求吗

**Comment by zhang-anzhi** [comment]
> > > [http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http这个可以吗](http://bbs.onoqq.com/forum.php?mod=viewthread&tid=575&highlight=http%E8%BF%99%E4%B8%AA%E5%8F%AF%E4%BB%A5%E5%90%97)
> > 
> > 
> > 功能不全。
> 
> 你能说说具体要求吗

不能，请自行了解本项目工作原理

**Comment by zhang-anzhi** [comment]
建议使用 [go-cqhttp](https://github.com/Mrs4s/go-cqhttp)，具体请查看readme
