### ISSUE TITLE
机器人可以转发服务端消息和接受QQ发送的命令，但服务端不响应命令

### ISSUE THREAD

**Issue by RisingInIris2017** [zhang-anzhi/CoolQAPI#4]
### 系统环境
OS: Windows Server 2019 Datacenter
JRE: 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.3.3) (build 1.8.0_242-b98)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.3.3) (build 25.242-b98, mixed mode)
```
### 机器人软件版本
cqhttp-mirai-0.2.3-embedded-all
#### MCDR 版本
0.9.6
#### 安装的插件
```
[MCDR] [19:17:30] [InfoReactor/INFO]: 8x 已加载插件
[MCDR] [19:17:30] [InfoReactor/INFO]: - CoolQAPI-MCDR.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - daycount.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - Here.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - joinMOTD.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - OnlinePlayerAPI.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - QQChat.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - QuickBackupM.py
[MCDR] [19:17:30] [InfoReactor/INFO]: - tps.py
[MCDR] [19:17:30] [InfoReactor/INFO]: 0x 已禁用插件
[MCDR] [19:17:30] [InfoReactor/INFO]: 0x 未加载插件
```
### 问题描述
我使用 cqhttp-mirai-0.2.3-embedded-all 机器人与安装有上述插件的服务端连接。
之前已经正常使用了一段时间，不久前服务器需要关机维护，重新启动以后出现了如下情况。

我的机器人配置文件：https://paste.ubuntu.com/p/smh6KZKh9S/
CoolQAPI 的 config.yml：https://paste.ubuntu.com/p/sktdpk33q7/
我先启动了机器人，登录了配置文件中的机器人 QQ 号之后，启动 MCDR，在 MCDR 启动过程中机器人可以不断向我配置好的管理员 QQ 号发送服务端启动中出现的控制台信息，可见配置是正常的。
但是我使用管理员 QQ 号向机器人发送 `/command list` 命令作为测试，在打开 MCDR 调试模式情况下，MCDR 控制台没有回显“收到上报数据”。

经检查，机器人在启动过程中有如下报错：
https://paste.ubuntu.com/p/jWyyxYHv28/

我能否确认这是机器人本身的问题，并向 cqhttp-mirai 的开发者反馈？
还是说是我的插件配置有某些问题，导致了机器人只能转发服务端消息，不能接收管理员 QQ 发送的命令？
希望可以得到你的帮助，谢谢！

**Comment by zhang-anzhi** [comment]
看报错是mirai无法上报数据，应该为网络问题
我没有遇到过这样的情况，并且看配置文件没有问题
能否详细描述一下 `“可以转发服务端消息和接受QQ发送的命令”` 你提到 `但是我使用管理员 QQ 号向机器人发送 /command list 命令作为测试，在打开 MCDR 调试模式情况下，MCDR 控制台没有回显“收到上报数据”。` 这看起来是冲突的，你能接收qq发送的命令还没有回显debug信息，这是不可能的

**Comment by RisingInIris2017** [comment]
> 能否详细描述一下 `“可以转发服务端消息和接受QQ发送的命令”` 你提到 `但是我使用管理员 QQ 号向机器人发送 /command list 命令作为测试，在打开 MCDR 调试模式情况下，MCDR 控制台没有回显“收到上报数据”。` 

是这样的：
- 机器人会把 MCDR 控制台的消息发给我；
- 我发消息给机器人，机器人的控制台能看到我发的消息；
- 但是同一条消息，在 MCDR 调试模式下，看不到“接收上报数据”的回显；
- 机器人不响应我发送的命令，包括/bound，/help等等，也包括/command命令。发送后机器人没有任何的响应，但是如第二条所说，机器人控制台是有现实的。

**Comment by zhang-anzhi** [comment]
请复制部分你向机器人发送信息后的mirai控制台日志，以及是否有报错

**Comment by RisingInIris2017** [comment]
> 请复制部分你向机器人发送信息后的mirai控制台日志，以及是否有报错

我通过 QQ 发送消息：
![0FBhX8.png](https://s1.ax1x.com/2020/09/27/0FBhX8.png)
mirai 控制台日志：
```[0m 10:31:49 [INFO] [BOT <机器人QQ号>] <管理员昵称>(<管理员QQ号>) -> [mirai:source:14074,591810119]/command list[39;49m```
没有报错。

MCDR 控制台没有反应。

如果还需要我提供其他的信息或者完成一些测试，我会尽量提供信息和测试结果。
非常感谢你的耐心帮助！

**Comment by zhang-anzhi** [comment]
请不要在强调你服务端可以发送消息到qq，这只能证明api正常
> 看报错是mirai无法上报数据
请复制向机器人发送消息后的多条控制台日志甚至mirai启动后到发送消息之后的完整日志
另外请将你的mirai插件配置文件和coolqapi配置文件发送，并核对mirai配置文件的qq号

**Comment by RisingInIris2017** [comment]
> 请不要在强调你服务端可以发送消息到qq，这只能证明api正常

抱歉我误会了你的意思。我现在将下面要求的这些内容补上。

> 请复制向机器人发送消息后的多条控制台日志甚至mirai启动后到发送消息之后的完整日志
> 另外请将你的mirai插件配置文件和coolqapi配置文件发送，并核对mirai配置文件的qq号

mirai 插件配置文件：
```yaml
'241685021':
  http:
    enable: true
    host: 127.0.0.1
    port: 5700
    postUrl: "http://127.0.0.1:5701/post"
    postMessageFormat: array
```
CoolQAPI 配置文件：
```yaml
post_host: 127.0.0.1
post_port: 5701
api_host: 127.0.0.1
api_port: 5700
command_prefix: /
```
Mirai 机器人从启动到发送消息时的完整日志：https://paste.ubuntu.com/p/FFdqZW8DG2/
在日志中我发送了不少消息，大部分是 `/command list` 和 `/command say`。
日志中机器人的 QQ 没有打码。

如果还有需要我提供的信息，我会尽量提供。
感谢你的耐心帮助！

**Comment by zhang-anzhi** [comment]
请在开启mcdr时运行以下python脚本
```python
import requests

data = {
    'time': 123,
    'post_type': 'test',
}
requests.post('http://127.0.0.1:5701/post', json=data)
```
若一切正常mcdr控制台应显示以下信息
![image](https://user-images.githubusercontent.com/37402126/94356139-91363580-00bd-11eb-9c96-8ab8673aa497.png)

**Comment by zhang-anzhi** [comment]
另外问一下在出现此问题之后你的服务器是否重启过，如没有先重启一遍再向机器人发送消息查看

**Comment by RisingInIris2017** [comment]
> 请在开启mcdr时运行以下python脚本
> 
> ```python
> import requests
> 
> data = {
>     'time': 123,
>     'post_type': 'test',
> }
> requests.post('http://127.0.0.1:5701/post', json=data)
> ```

我尝试了两种加载途径：
一种是将上述脚本保存为 robottest.py，放入 `<MCDRdir>/plugins` 文件夹中，然后用 `!!MCDR reload plugin` 重载 MCDR 插件，控制台回显如下：
```
!!MCDR reload plugin
[MCDR] [18:23:00] [Console/DEBUG]: Parsed text from console input:
[MCDR] [18:23:00] [Console/DEBUG]:     Time: 18:23:00; ID: 1014
[MCDR] [18:23:00] [Console/DEBUG]:     Player: None; Source: 1; Logging level: None
[MCDR] [18:23:00] [Console/DEBUG]:     Content: !!MCDR reload plugin
[MCDR] [18:23:00] [Console/DEBUG]:     Raw content: !!MCDR reload plugin
[MCDR] [18:23:00] [InfoReactor/INFO]: 加载插件中
[MCDR] [18:23:00] [CoolQAPI server/DEBUG]: 接收上报数据{
    "time": 123,
    "post_type": "test"
}
[MCDR] [18:23:00] [InfoReactor/DEBUG]: Plugin plugins\robottest.py loaded, file sha256 = fe5264d1ccde7f9849c44b35f1b59c59fb7e25421d922e455d5888e8b880e5fc
[MCDR] [18:23:00] [InfoReactor/INFO]: 插件 robottest.py 已加载
[MCDR] [18:23:00] [InfoReactor/INFO]: 已加载: 1 个插件; 已加载插件总数: 9
```

另一种是将保存好的上述脚本移到 MCDR 路径以外，重载 MCDR，然后双击运行脚本，同样可以看到
```
[MCDR] [18:24:11] [CoolQAPI server/DEBUG]: 接收上报数据{
    "time": 123,
    "post_type": "test"
}
```
我想这应该意味着我的配置是正常的，我会尝试一下重启服务器再执行上述测试。

**Comment by zhang-anzhi** [comment]
那就是你的mirai出了问题，尝试修复或重新配置mirai

**Comment by RisingInIris2017** [comment]
问题已经解决，解决方法是改变启动顺序，先启动 MCDR，等 MCDR 抛出未能连接到机器人的异常后，再启动 Mirai 机器人并登陆 QQ 账号。
感谢你的耐心指导和帮助！
