### ISSUE TITLE
使用go-cqhttp不清楚反向HTTP POST地址如何填

### ISSUE THREAD

**Issue by DancingSnow0517** [zhang-anzhi/CoolQAPI#5]
![image](https://user-images.githubusercontent.com/60736156/116750985-e6f90480-aa35-11eb-900c-3df36ef34f2f.png)
按照这么填，程序总是提示上报失败
![image](https://user-images.githubusercontent.com/60736156/116751022-fc6e2e80-aa35-11eb-8fed-c827f0d1684a.png)

**Comment by zhang-anzhi** [comment]
出错的原因是提供了secret，改成 `"127.0.0.1:5701/post": ""` 即可
