### ISSUE TITLE
QQ机器人只能推送开服消息，其他消息无法推送

### ISSUE THREAD

**Issue by TNTobsidian** [zhang-anzhi/CoolQAPI#6]
### 系统环境
OS：Windows Datacenter 2019
jre: `java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)`
### CQHTTP版本
v1.0.0-beta4  17d9830
### MCDR信息
`
[MCDR] [07:12:01] [TaskExecutor/INFO]: MCDReforged 版本: 1.5.1
[MCDR] [07:12:01] [TaskExecutor/INFO]: MCDR 状态: 运行中
[MCDR] [07:12:01] [TaskExecutor/INFO]: 服务端状态: 运行中
[MCDR] [07:12:01] [TaskExecutor/INFO]: 服务端已启动: True
[MCDR] [07:12:01] [TaskExecutor/INFO]: 将于服务端关闭后退出: True
[MCDR] [07:12:01] [TaskExecutor/INFO]: rcon: 离线
[MCDR] [07:12:01] [TaskExecutor/INFO]: 插件数量: 24
[MCDR] [07:12:01] [TaskExecutor/INFO]: 服务端 PID: 5724
[MCDR] [07:12:01] [TaskExecutor/INFO]: 消息队列负载: 0/2048
[MCDR] [07:12:01] [TaskExecutor/INFO]: 线程数: 6
[MCDR] [07:12:01] [TaskExecutor/INFO]:   - MainThread
[MCDR] [07:12:01] [TaskExecutor/INFO]:   - TaskExecutor
[MCDR] [07:12:01] [TaskExecutor/INFO]:   - CoolQAPI server
[MCDR] [07:12:01] [TaskExecutor/INFO]:   - ConsoleHandler
[MCDR] [07:12:01] [TaskExecutor/INFO]:   - UpdateHelper
[MCDR] [07:12:01] [TaskExecutor/INFO]:   - WatchDog`
插件
`[MCDR] [07:12:50] [TaskExecutor/INFO]: 24x 已加载插件
[MCDR] [07:12:50] [TaskExecutor/INFO]: - beep (beep@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - ConfigAPI (config_api@0.0.3)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - CoolQAPI (cool_q_api@0.2.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - DayCount-NBT (daycount_nbt@1.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - deathpos (deathpos@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - Gamemode (gamemode@0.0.1)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - JsonDataAPI (json_data_api@0.0.1)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - Markit (markit@1.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - Task (mcd_task@1.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - MCDReforged (mcdreforged@1.5.1)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - Minecraft Data API (minecraft_data_api@1.2.2)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - online (online@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - OnlinePlayerAPI (online_player_api@0.0.1)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - playerinfoapi (playerinfoapi@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - QQChat (qq_chat@0.0.3)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - Quick Backup Multi (quick_backup_multi@1.1.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - RText Exp (rtext_exp@0.0.1)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - seen (seen@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - startstophelper (startstophelper@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - statshelper (statshelper@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - stext (stext@1.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - tpa (tpa@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - tphelper (tphelper@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: - vote (vote@0.0.0)
[MCDR] [07:12:50] [TaskExecutor/INFO]: 0x 已禁用插件
[MCDR] [07:12:50] [TaskExecutor/INFO]: 1x 未加载插件
[MCDR] [07:12:50] [TaskExecutor/INFO]: - joinMOTD.py`

### 问题描述
CQHTTP可以正常链接并且接收信息，可以在开服时推送开服消息。
![image](https://user-images.githubusercontent.com/65720409/121805089-2bee9880-cc7c-11eb-8b71-a6429989e7cb.png)
CQHTTP后台可以看见我发的消息
![image](https://user-images.githubusercontent.com/65720409/121805123-5b9da080-cc7c-11eb-8b7c-8d65ebe1720f.png)
但是MC服务器中无法接收信息，也无法转发信息至QQ群，不知道是哪里出了问题
机器人配置：https://paste.ubuntu.com/p/KXwjRXDDDJ/
CoolQAPI配置：`api_host: 127.0.0.1
api_port: 5700
command_prefix: /
post_host: 127.0.0.1
post_path: post
post_port: 5701`
参照#4中的内容，我尝试启动下面的脚本：
```
import requests

data = {
    'time': 123,
    'post_type': 'test',
}
requests.post('http://127.0.0.1:5701/post', json=data)
```

但是什么都没发生就退出了。请问和这个有关吗，如何解决？如果需要提供更多信息我会积极配合，谢谢！

**Comment by zhang-anzhi** [comment]
配置问题，建议咨询群里其他人，不属于软件问题

**Comment by TaiChi01** [comment]
> ### 系统环境
> OS：Windows Datacenter 2019
> jre: `java version "1.8.0_291" Java(TM) SE Runtime Environment (build 1.8.0_291-b10) Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)`
> 
> ### CQHTTP版本
> v1.0.0-beta4 17d9830
> 
> ### MCDR信息
> ` [MCDR] [07:12:01] [TaskExecutor/INFO]: MCDReforged 版本: 1.5.1 [MCDR] [07:12:01] [TaskExecutor/INFO]: MCDR 状态: 运行中 [MCDR] [07:12:01] [TaskExecutor/INFO]: 服务端状态: 运行中 [MCDR] [07:12:01] [TaskExecutor/INFO]: 服务端已启动: True [MCDR] [07:12:01] [TaskExecutor/INFO]: 将于服务端关闭后退出: True [MCDR] [07:12:01] [TaskExecutor/INFO]: rcon: 离线 [MCDR] [07:12:01] [TaskExecutor/INFO]: 插件数量: 24 [MCDR] [07:12:01] [TaskExecutor/INFO]: 服务端 PID: 5724 [MCDR] [07:12:01] [TaskExecutor/INFO]: 消息队列负载: 0/2048 [MCDR] [07:12:01] [TaskExecutor/INFO]: 线程数: 6 [MCDR] [07:12:01] [TaskExecutor/INFO]: - MainThread [MCDR] [07:12:01] [TaskExecutor/INFO]: - TaskExecutor [MCDR] [07:12:01] [TaskExecutor/INFO]: - CoolQAPI server [MCDR] [07:12:01] [TaskExecutor/INFO]: - ConsoleHandler [MCDR] [07:12:01] [TaskExecutor/INFO]: - UpdateHelper [MCDR] [07:12:01] [TaskExecutor/INFO]: - WatchDog`
> 插件
> `[MCDR] [07:12:50] [TaskExecutor/INFO]: 24x 已加载插件 [MCDR] [07:12:50] [TaskExecutor/INFO]: - beep (beep@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - ConfigAPI (config_api@0.0.3) [MCDR] [07:12:50] [TaskExecutor/INFO]: - CoolQAPI (cool_q_api@0.2.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - DayCount-NBT (daycount_nbt@1.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - deathpos (deathpos@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - Gamemode (gamemode@0.0.1) [MCDR] [07:12:50] [TaskExecutor/INFO]: - JsonDataAPI (json_data_api@0.0.1) [MCDR] [07:12:50] [TaskExecutor/INFO]: - Markit (markit@1.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - Task (mcd_task@1.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - MCDReforged (mcdreforged@1.5.1) [MCDR] [07:12:50] [TaskExecutor/INFO]: - Minecraft Data API (minecraft_data_api@1.2.2) [MCDR] [07:12:50] [TaskExecutor/INFO]: - online (online@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - OnlinePlayerAPI (online_player_api@0.0.1) [MCDR] [07:12:50] [TaskExecutor/INFO]: - playerinfoapi (playerinfoapi@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - QQChat (qq_chat@0.0.3) [MCDR] [07:12:50] [TaskExecutor/INFO]: - Quick Backup Multi (quick_backup_multi@1.1.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - RText Exp (rtext_exp@0.0.1) [MCDR] [07:12:50] [TaskExecutor/INFO]: - seen (seen@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - startstophelper (startstophelper@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - statshelper (statshelper@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - stext (stext@1.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - tpa (tpa@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - tphelper (tphelper@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: - vote (vote@0.0.0) [MCDR] [07:12:50] [TaskExecutor/INFO]: 0x 已禁用插件 [MCDR] [07:12:50] [TaskExecutor/INFO]: 1x 未加载插件 [MCDR] [07:12:50] [TaskExecutor/INFO]: - joinMOTD.py`
> 
> ### 问题描述
> CQHTTP可以正常链接并且接收信息，可以在开服时推送开服消息。
> ![image](https://user-images.githubusercontent.com/65720409/121805089-2bee9880-cc7c-11eb-8b71-a6429989e7cb.png)
> CQHTTP后台可以看见我发的消息
> ![image](https://user-images.githubusercontent.com/65720409/121805123-5b9da080-cc7c-11eb-8b7c-8d65ebe1720f.png)
> 但是MC服务器中无法接收信息，也无法转发信息至QQ群，不知道是哪里出了问题
> 机器人配置：https://paste.ubuntu.com/p/KXwjRXDDDJ/
> CoolQAPI配置：`api_host: 127.0.0.1 api_port: 5700 command_prefix: / post_host: 127.0.0.1 post_path: post post_port: 5701`
> 参照#4中的内容，我尝试启动下面的脚本：
> 
> ```
> import requests
> 
> data = {
>     'time': 123,
>     'post_type': 'test',
> }
> requests.post('http://127.0.0.1:5701/post', json=data)
> ```
> 
> 但是什么都没发生就退出了。请问和这个有关吗，如何解决？如果需要提供更多信息我会积极配合，谢谢！

您好我和你一样的问题，请问你解决了么，需要修改什么配置呢？
